apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: add
  name: add
  namespace: calculator
spec:
  lookupPolicy:
    local: true
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000
  tags:
  - items:
    tag: latest
